export const AUTH_AGENT_REPOSITORY = Symbol('AUTH_AGENT_REPOSITORY');
export const AUTH_PASSWORD_VERIFIER = Symbol('AUTH_PASSWORD_VERIFIER');
export const AUTH_SHIFT_TOKEN_SIGNER = Symbol('AUTH_SHIFT_TOKEN_SIGNER');
export const AUTH_CONFIG = Symbol('AUTH_CONFIG');
export const AUTH_REFRESH_TOKEN_REPOSITORY = Symbol('AUTH_REFRESH_TOKEN_REPOSITORY');
