export const LINKS_CONFIG = Symbol('LINKS_CONFIG');
export const MAGIC_LINKS_REPOSITORY = Symbol('MAGIC_LINKS_REPOSITORY');
export const MAGIC_LINK_TOKEN_GENERATOR = Symbol('MAGIC_LINK_TOKEN_GENERATOR');
