export const CUSTOMER_SESSIONS_REPOSITORY = Symbol('CUSTOMER_SESSIONS_REPOSITORY');
export const CUSTOMER_SESSION_TOKEN_SIGNER = Symbol('CUSTOMER_SESSION_TOKEN_SIGNER');
export const SESSIONS_CONFIG = Symbol('SESSIONS_CONFIG');
