import { StyleSheet } from 'react-native'
import { palette, radius, spacing, touchTarget } from '../theme/tokens'

type CreateSupervisorStylesParams = {
  isRtlLayout: boolean
  numericFontFamily: string
  scaledFont: (value: number) => number
}

export function createSupervisorStyles({
  isRtlLayout,
  numericFontFamily,
  scaledFont,
}: CreateSupervisorStylesParams) {
  return StyleSheet.create({
    supervisorControlHeaderCard: {
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surface,
      padding: spacing.md,
      flexDirection: isRtlLayout ? 'row-reverse' : 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    supervisorControlHeading: {
      flex: 1,
      flexDirection: isRtlLayout ? 'row-reverse' : 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    supervisorControlIconWrap: {
      width: 34,
      height: 34,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surfaceLow,
      alignItems: 'center',
      justifyContent: 'center',
    },
    supervisorControlHeadingText: {
      flex: 1,
      gap: 2,
    },
    supervisorControlTitle: {
      color: palette.primary,
      fontWeight: '800',
      fontSize: scaledFont(17),
      textAlign: isRtlLayout ? 'right' : 'left',
      writingDirection: isRtlLayout ? 'rtl' : 'ltr',
    },
    supervisorControlMeta: {
      color: palette.secondary,
      fontWeight: '600',
      fontSize: 12,
      fontFamily: numericFontFamily,
      fontVariant: ['tabular-nums'],
      textAlign: isRtlLayout ? 'right' : 'left',
      writingDirection: isRtlLayout ? 'rtl' : 'ltr',
    },
    supervisorRefreshButton: {
      minHeight: touchTarget.min,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surfaceLow,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
      flexDirection: isRtlLayout ? 'row-reverse' : 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    supervisorRefreshButtonText: {
      color: palette.secondary,
      fontWeight: '700',
      fontSize: 12,
    },
    supervisorWorkspaceTabsContainer: {
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surface,
      paddingVertical: spacing.xs,
      paddingHorizontal: spacing.xs,
    },
    supervisorWorkspaceTabsContent: {
      flexDirection: isRtlLayout ? 'row-reverse' : 'row',
      gap: spacing.xs,
      width: '100%',
    },
    supervisorWorkspaceTab: {
      flex: 1,
      minWidth: 0,
      minHeight: touchTarget.min,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surfaceLow,
      paddingHorizontal: spacing.xs,
      flexDirection: isRtlLayout ? 'row-reverse' : 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    supervisorWorkspaceTabActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primaryContainer,
    },
    supervisorWorkspaceTabLabel: {
      color: palette.secondary,
      fontWeight: '700',
      fontSize: 12,
      textAlign: 'center',
    },
    supervisorWorkspaceTabLabelActive: {
      color: '#fff',
    },
    supervisorWorkspaceInfoCard: {
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surfaceLow,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      flexDirection: isRtlLayout ? 'row-reverse' : 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    supervisorWorkspaceInfoText: {
      flex: 1,
      color: palette.secondary,
      fontWeight: '700',
      fontSize: 12,
      textAlign: isRtlLayout ? 'right' : 'left',
      writingDirection: isRtlLayout ? 'rtl' : 'ltr',
    },
    supervisorOversightMetricsGrid: {
      flexDirection: isRtlLayout ? 'row-reverse' : 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    supervisorOversightMetricCard: {
      flexGrow: 1,
      minWidth: 132,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surfaceLow,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      gap: 2,
    },
    supervisorOversightMetricLabel: {
      color: palette.textMuted,
      fontSize: 11,
      fontWeight: '700',
    },
    supervisorOversightMetricValue: {
      color: palette.primaryContainer,
      fontSize: scaledFont(18),
      fontWeight: '800',
      fontFamily: numericFontFamily,
      fontVariant: ['tabular-nums'],
    },
    supervisorOversightColumns: {
      gap: spacing.sm,
    },
    supervisorOversightColumn: {
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surfaceLow,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      gap: spacing.xs,
    },
    supervisorOversightList: {
      gap: spacing.xs,
    },
    supervisorOversightRow: {
      gap: 2,
    },
    supervisorOversightRowPrimary: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '800',
      textAlign: isRtlLayout ? 'right' : 'left',
      writingDirection: isRtlLayout ? 'rtl' : 'ltr',
    },
    supervisorOversightRowMeta: {
      color: palette.textMuted,
      fontSize: 11,
      fontWeight: '700',
      fontFamily: numericFontFamily,
      fontVariant: ['tabular-nums'],
      textAlign: isRtlLayout ? 'right' : 'left',
      writingDirection: isRtlLayout ? 'rtl' : 'ltr',
    },
    supervisorNotesInput: {
      minHeight: 96,
      paddingTop: 10,
    },
    supervisorStatusRow: {
      flexDirection: isRtlLayout ? 'row-reverse' : 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    supervisorAgentHint: {
      color: palette.textMuted,
      fontSize: 12,
      fontWeight: '600',
      textAlign: isRtlLayout ? 'right' : 'left',
      writingDirection: isRtlLayout ? 'rtl' : 'ltr',
    },
    supervisorDangerActionButton: {
      backgroundColor: palette.dangerSurface,
      borderWidth: 1,
      borderColor: palette.danger,
    },
    supervisorDangerActionText: {
      color: palette.danger,
      fontWeight: '700',
      fontSize: 13,
      textAlign: 'center',
    },
    supervisorAssignmentList: {
      gap: spacing.sm,
    },
    supervisorBulkColumns: {
      gap: spacing.sm,
    },
    supervisorBulkColumn: {
      gap: spacing.xs,
    },
    supervisorBulkLabel: {
      color: palette.secondary,
      fontSize: 12,
      fontWeight: '700',
    },
    supervisorAssignmentRow: {
      flexDirection: isRtlLayout ? 'row-reverse' : 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: palette.outline,
      borderRadius: radius.md,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      backgroundColor: palette.surfaceLow,
      gap: spacing.sm,
    },
    supervisorAssignmentMeta: {
      flex: 1,
      gap: 2,
    },
    supervisorAssignmentAgent: {
      color: palette.primary,
      fontSize: 14,
      fontWeight: '800',
    },
    supervisorAssignmentDate: {
      color: palette.textMuted,
      fontSize: 12,
      fontWeight: '600',
      fontFamily: numericFontFamily,
      fontVariant: ['tabular-nums'],
    },
    supervisorUnassignText: {
      color: palette.danger,
      fontSize: 13,
      fontWeight: '700',
      textDecorationLine: 'underline',
    },
    supervisorAuditList: {
      gap: spacing.sm,
    },
    supervisorAuditRow: {
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surfaceLow,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      gap: 4,
    },
    supervisorAuditEvent: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '800',
    },
    supervisorAuditMeta: {
      color: palette.textMuted,
      fontSize: 11,
      fontWeight: '600',
      fontFamily: numericFontFamily,
      fontVariant: ['tabular-nums'],
    },
  })
}
