name: awawda-local-infra

services:
  postgres:
    image: postgres:16.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: awawda
    ports:
      - '55432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - awawda-local

  redis:
    image: redis:7.2.5-alpine
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes', '--save', '60', '1000']
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - awawda-local

volumes:
  postgres_data:
  redis_data:

networks:
  awawda-local:
    driver: bridge
